### PR TITLE
Remove OAuthSignatureCheckingFilter

### LINKED ISSUE #141: OAuthSignatureCheckingFilter prevents developers to use http
OAuthSignatureCheckingFilter.java is transforming the protocol in the signature base string from http to https.
This prevent the signature tu be validated if the oauth signature was perform using http.

Instead, to proper support protocol change (from https to http) developer should add the following spring configuration:
```
server:
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for
```

This will activate RemoteIpValve.java which will take care of the protocol replacement using the `x-forwarded-proto` header

### PR DESCRIPTION
**Pull request by davidchau**
OAuthSignatureCheckingFilter.java is transforming the protocol in the signature base string from http to https.
This prevent the signature tu be validated if the oauth signature was perform using http.

Instead, to proper support protocol change (from https to http) developer should add the following spring configuration:
```
server:
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for
```

This will activate RemoteIpValve.java which will take care of the protocol replacement using the `x-forwarded-proto` header 

resolves #141

- [ ] Approved by a PI tech lead

### CODE REVIEW

**Comment by jpboudreault** [comment]
@davidchau please update CPC

**Comment by ian-beckles** [comment]
@davidchau @jpboudreault @hooriak, Don't we also need to set another value here. Maybe I am misreading this.

From https://docs.spring.io/spring-security/oauth1.x/apidocs/org/springframework/security/oauth/provider/filter/ProtectedResourceProcessingFilter.html

Processing filter for requests to protected resources. This filter attempts to load the OAuth authentication request into the security context using a presented access token. Default behavior of this filter allows the request to continue even if OAuth credentials are not presented (allowing another filter to potentially load a different authentication request into the security context). If the protected resource is available ONLY via OAuth access token, set ignoreMissingCredentials to false.

**Comment by davidchau** [comment]
you might be right. 
so If the flag is true (which I think is by default) the OAuth signature seems to be optional, I am understanding it correctly? 
I have a PR with GoDaddy connector on which we can test it easily.

**Comment by ian-beckles** [comment]
@davidchau, Yeah that's the way I understand the documentation as well. Cool on the testing, because we definitely don't want the OAuth signature being optional. Also while you are testing please also make sure that the /health and /info urls still work as expected.

**Comment by hooriak** [comment]
Based on the description it does look like we need to explicitly set the value to false.

**Pull request merged**
