### PR TITLE
Added configuration to AddOnSubscriptionOrder

### PR DESCRIPTION
**Pull request by jonfk**
JIRA ticket:

- [ ] Approved by a PI tech lead

### CODE REVIEW

**Comment by aaiezza** [comment]
This is definitely a change that will be useful, but would you consider just including the `configuration` portion of the payload in the `EventWithContext` super class?

(See PR [167](https://github.com/AppDirect/service-integration-sdk/pull/167))

**Comment by jonfk** [comment]
I think that would work. The only thing I worry about is that currently, we have encoded which events have a configuration and which ones don't. We know for example that user events don't have configuration payloads since they don't have purchase orders. If we can maybe mention that in documentation I would be ok with that.

**Comment by aaiezza** [comment]
@jonfk, that is a good point. Would you feel comfortable making that case on my current PR. I wouldn't mind accommodating that change if it would be a better practice to do so.

I would have in mind to create another interface `EventWithContextWithConfiguration` or something like that, that subscription events would implement instead. Then, user events would remain unchanged along with the original `EventWithContext`.
Thoughts?

**Comment by aaiezza** [comment]
Given that this work is accomplished by PR #168, I might suggest to close this one. @jonfk thanks again for your help on this one.

**Pull request closed without merging**
